### PR TITLE
Remove quotes from the environment path

### LINKED ISSUE #581: Environment variable configured by CQtDeployer's own installer on Windows should not be quoted
**Describe the bug**
Because of the quotes, the environment variable configured by CQtDeployer's own installer doesn't work properly in PowerShell on Windows.

**To Reproduce**
1. Open PowerShell.
2. Check the environment variables configured by CQtDeployer's installer via `Get-Item -Path Env:\cqt*` ([Getting environment variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_provider#getting-environment-variables)).
3. Try to call CQtDeployer via `& ${Env:\cqtdeployer}` , failed ([Call operator `&`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators#call-operator-) ).
4. Try to change the working directory to the installation location via `Set-Location -Path ${Env:\cqtDir}` , failed ([Set-Location](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-location)).
5. If I remove these quotes, everything works fine.

**Expected behavior**
Use those variables normally.

**Console output**

Errors:

```console
PS C:\> Get-Item -Path Env:\cqt*

Name                           Value
----                           -----
cqtDir                         "C:\Program Files (x86)\CQtDeployer\1.4\"
CQTDEPLOYER_VERSION            1.4.7
cqtdeployer                    "C:\Program Files (x86)\CQtDeployer\1.4\cqtdeployer.bat"

PS C:\> & ${Env:\cqtdeployer}
&: The term '"C:\Program Files (x86)\CQtDeployer\1.4\cqtdeployer.bat"' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

PS C:\> Set-Location -Path ${Env:\cqtDir}
Set-Location: Cannot find drive. A drive with the name '"C' does not exist.
```

After removing quotes:

```console
PS C:\> ${Env:\cqtdeployer} = ${Env:\cqtdeployer}.Trim('"')
PS C:\> ${Env:\cqtDir} = ${Env:\cqtDir}.Trim('"')

PS C:\> Get-Item -Path Env:\cqt*

Name                           Value
----                           -----
cqtDir                         C:\Program Files (x86)\CQtDeployer\1.4\
CQTDEPLOYER_VERSION            1.4.7
cqtdeployer                    C:\Program Files (x86)\CQtDeployer\1.4\cqtdeployer.bat

PS C:\> & ${Env:\cqtdeployer}
Info: Print info ...
...

PS C:\> Set-Location -Path ${Env:\cqtDir}
PS C:\Program Files (x86)\CQtDeployer\1.4>
```

**Desktop:**
 - OS: Windows 10 2004 10.0.19041.867
 - PowerShell
   - 5.1.19041.610
   - 7.1.2

**Additional context**
Some code in project may need to be modified:

- https://github.com/QuasarApp/CQtDeployer/blob/78845ef8d5ad3f7af7cfdedbcdabeb7cd00ae5c6/test.pri#L11
- https://github.com/QuasarApp/CQtDeployer/blob/78845ef8d5ad3f7af7cfdedbcdabeb7cd00ae5c6/QIFData/InstallerBase.pri#L7

Diff:

```diff
-  win32:DEPLOYER=$$(cqtdeployer)
+  win32:DEPLOYER="$$(cqtdeployer)" 
```

Let me know if you have any questions about ~PowerShell~ this issue (sorry).

### PR DESCRIPTION
**Pull request by EndrII**
fix #581 

## Note 
need to manually tests.

### CODE REVIEW

**Comment by pzhlkj6612** [comment]
Hi.

1. As I said in https://github.com/QuasarApp/CQtDeployer/issues/581#issuecomment-829740659 , unconditionally adding quotes may break the program. I‘m thinking of another way now.
2. You forgot CQtDeployer/test.pri .
3. I didn't even know that these environment variables are stored in this repository (that is, QIFData/packages/cqtdeployer*/meta/installscript.js ). I was too careless.

**Comment by EndrII** [comment]
>     1. As I said in [#581 (comment)](https://github.com/QuasarApp/CQtDeployer/issues/581#issuecomment-829740659) , unconditionally adding quotes may break the program. I‘m thinking of another way now.

now we can check it out. look at the test results.

**Comment by EndrII** [comment]
@pzhlkj6612 it seems the extra quotes didn't break anything.

**Comment by EndrII** [comment]
@pzhlkj6612 please check this fix manually on cmd and powershell
[download link](https://quasarapp.ddns.net:3031/QuasarApp/CQtDeployer/9dd5da5121456ab8dbd6ea33af76351a7b17a78d/CQtDeployerOfflineInstaller.exe)

**Comment by pzhlkj6612** [comment]
> ... it seems the extra quotes didn't break anything.

Yes, it does.

Please wait for my further testing.

**Comment by pzhlkj6612** [comment]
> > ... it seems the extra quotes didn't break anything.
> 
> Yes, it does.

Well, I mean, it didn't break anything in my previous testing.

<br>

I need to learn more English.

**Comment by EndrII** [comment]
> > > ... it seems the extra quotes didn't break anything.
> > 
> > 
> > Yes, it does.
> 
> Well, I mean, it didn't break anything in my previous testing.
> 
> I need to learn more English.

do you test on this [build](https://quasarapp.ddns.net:3031/QuasarApp/CQtDeployer/9dd5da5121456ab8dbd6ea33af76351a7b17a78d/CQtDeployerOfflineInstaller.exe)

**Comment by pzhlkj6612** [comment]
Hi. Since testing CQtDeployer after building needs an already installed CQtDeployer, I want to know what version of CQtDeployer is installed on your CI.

**Comment by EndrII** [comment]
> Hi. Since testing CQtDeployer after building needs an already installed CQtDeployer, I want to know what version of CQtDeployer is installed on your CI.

I tested it on CI all is fine.

**Comment by pzhlkj6612** [comment]
I mean, the already installed CQtDeployer seems to affect the behavior of test.  
Could you please provide the version number of CQtDeployer which is installed on your CI?

**Comment by EndrII** [comment]
#Tested on build bot CI. (replace stable version of  cqtdeployer)

**Pull request merged**
