### PR TITLE
Added documentation for disabling standard shortcuts

### PR DESCRIPTION
**Pull request by EndrII**
## Documentation 
* added article "Disable standard shortcuts"

## Bug fixes:
* Fix create qifw installers with noOverwrite option.

### CODE REVIEW

**Comment by pzhlkj6612** [comment]
Hi. I think I can review this within 72 hours.

**Comment by EndrII** [comment]
@pzhlkj6612 okay hanks

**Comment by EndrII** [comment]
This PR contains changes that which should get into the beta version of cqtdeployer 1.5. for this reason, I close this pool request to open it for the v1.5beta branch

**Comment by pzhlkj6612** [comment]
Oops.

**Comment by EndrII** [comment]
see #569

**Pull request closed without merging**
