### PR TITLE
Remove dependency of the qif package

### LINKED ISSUE #589: QIF will always be installed even though I didn't select it
**Describe the bug**

Qt Installer Framework (QIF) will always be installed with CQtDeployer even though I didn't select it.

**To Reproduce**

1. Download the online or offline installer and execute it. 
2. Don't select the "Qt Installer Framework" component.
3. Continue the installation and note the output in the "details" box.
4. Installation finished. QIF binaries can be found in the "QIF" folder of the installation path.

**Expected behavior**

If QIF is required by CQtDeployer, it should not be deselected when selecting CQtDeployer.

**Output details of installer**

Online installer:

```
Preparing the installation...

Downloading packages...
Downloading archive "4.1.0.2QIF.7z.sha1" for component Qt Installer Framework.
Downloading archive "4.1.0.2QIF.7z" for component Qt Installer Framework.
Downloading archive "1.4.7.31.4.7z.sha1" for component CQtDeployer 1.4.
Downloading archive "1.4.7.31.4.7z" for component CQtDeployer 1.4.

Installing component Qt Installer Framework...
Extracting "4.1.0.2QIF.7z"
Done

Installing component CQtDeployer 1.4...
Extracting "1.4.7.31.4.7z"
Done
Writing maintenance tool.

Installation finished!
```

Offline installer:

```
Preparing the installation...

Installing component Qt Installer Framework...
Extracting "4.0.0QIF.7z"
Done

Installing component CQtDeployer 1.4...
Extracting "1.4.7.01.4.7z"
Done
Writing maintenance tool.

Installation finished!
```

**Environment**

Desktop:
  - Windows 10
    - 1909 10.0.18363.418
    - 2004 10.0.19041.867
  - Ubuntu 20.04.0

### PR DESCRIPTION
**Pull request by EndrII**
fix #589

### CODE REVIEW

**Comment by pzhlkj6612** [comment]
Hi. Could you please upload the offline installer built by CI?

**Comment by EndrII** [comment]
https://quasarapp.ddns.net:3031/QuasarApp/CQtDeployer/f9b25b270cb21a6a1e48b3d738e025bc5860ad57/

**Comment by pzhlkj6612** [comment]
Test result:  
The offline installer works as expected, but the online installer still wants to install QIF.

**Comment by EndrII** [comment]
> Test result:
> The offline installer works as expected, but the online installer still wants to install QIF.

yes. because online installer download  information of dependency from server with outdated packages.

**Comment by pzhlkj6612** [comment]
So, the outdated info will be replaced with updated one after releasing v1.5 ?

**Comment by EndrII** [comment]
> So, the outdated info will be replaced with updated one after releasing v1.5 ?

yes

**Review by pzhlkj6612 — APPROVED** [review]
It works.

**Pull request merged**
