### PR TITLE
Added supports icons for targets.

### PR DESCRIPTION
**Pull request by EndrII**
This PR change a logic of the **icon** option.
Now the **icon** option set icons pathes for targets.
Example : 
```bash
cqt myTarget1,myTarget2 -icon myTarget1;path/to/icon1.png,myTarget2;path/to/icon2.png
```

### CODE REVIEW

**Comment by pzhlkj6612** [comment]
Hi. I will review this in a few days.

**Comment by EndrII** [comment]
> Hi. I will review this in a few days.

oh this is an urgent task, it should hit the v1.5 branch before Monday.

So I propose to make a deferred review, during any period you will make a review of already merged PR. and if you find bugs you will create a new PR with corrections or comments.

@pzhlkj6612  do you agree ?

**Comment by EndrII** [comment]
i prepare build of this branch for testing.

* [Linux](https://quasarapp.ddns.net:3031/CQtDeployer/(10_24)_02-27-2021/) 
* [Windows](https://quasarapp.ddns.net:3031/CQtDeployer/(10_29)_02-27-2021/)

**Comment by pzhlkj6612** [comment]
> So I propose to make a deferred review, during any period you will make a review of already merged PR. and if you find bugs you will create a new PR with corrections or comments.

Ok, go ahead.

**Pull request merged**
